package br.com.dominio.cpfweb.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
@NoArgsConstructor
@Getter
@Setter
@Data
@ToString
@EqualsAndHashCode
@DynamoDBTable(tableName = "LocalizaCPF")
public class ModelCPF {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Long id;
    private String token;
    private String CPF;
    private String data_nascimento;
    private String plugin;



}
